### ISSUE TITLE
Setup release process: staging deployment

### ISSUE THREAD

**Issue by bzz** [src-d/code-annotation#8]
We want this application to have same level of automation of release/deploy process as https://github.com/src-d/landing or https://github.com/src-d/blog does when a Tag triggers the deployment to a known-url.

This would include creating appropriate `.drone.yml` as well as working \w internal Infra team under separate issue, in order to apply it and make the deploy happen.

**Comment by smacker** [comment]
Blocked: needs input from infra

**Comment by rporres** [comment]
Can you set a quick meeting so that I understand better the requirements for this? thx!

**Comment by bzz** [comment]
Sure, let me setup one asap

**Comment by bzz** [comment]
Moving back to in-progress after discussion IRL.

**Comment by smacker** [comment]
Status update:
- PR with helm & drone is ready to be merged
- We tested configuration on cluster, it works

I don't merge the PR because we need working docker file. It's covered in #34.

After merging we will need to check all the flow from the start to the end. Most probably some env variables are missed somewhere.
